SELECT @@transaction_isolation;

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT balance FROM accounts WHERE id = 1;

START TRANSACTION;
UPDATE accounts SET balance = 1300.00 WHERE id = 1;

SELECT balance FROM accounts WHERE id = 1;

SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT balance FROM accounts WHERE id = 3;

START TRANSACTION;
UPDATE accounts SET balance = 8000.50 WHERE id = 3;
COMMIT;

SELECT balance FROM accounts WHERE id = 3;

SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
START TRANSACTION;
SELECT balance FROM accounts WHERE type = 'checking';

START TRANSACTION;
INSERT INTO accounts VALUES (6, 'Eve Checking', 'checking', 400.00);
COMMIT;